#!/usr/bin/python 
# by: Floriane Coulmance: 31.10.2025 

import os

BASE_DIR="/fs/dss/work/doau0129/hamlet_pheno/"  # hamlet_pheno/
GENO_DIR=os.path.join(BASE_DIR, "2_popgen")
PHENO_DIR = os.path.join(BASE_DIR, "1_phenotyping/pca")
SAMPLES_FILE=os.path.join(BASE_DIR, "metadata/geno_names.txt")
VCF_FILE=os.path.join(BASE_DIR, "phyps2e_m2.vcf.gz")
GXP_FILE=os.path.join(BASE_DIR, "metadata/color_gxp_peaks.txt")


FIGURES_DIR = os.path.join(BASE_DIR, "figures")
SCRIPTS_DIR = os.path.join(BASE_DIR, "scripts")
PYTHON_SCRIPT = os.path.join(SCRIPTS_DIR, "python", "permanova.py")
R_SCRIPT = os.path.join(SCRIPTS_DIR, "R", "Fig2_S11-S21.R")
SPID_SCRIPT = os.path.join(SCRIPTS_DIR, "sh", "vcf2nh.spid")

# Separate datasets into "location" and "species" groups
locations = ["arc","bar","bel","boc","flk","gun","hon","liz","pri","qui"]
species = ["abe","aff","atl","chl","gem","gum","gut","ind","nig","pue","ran","tan","uni","may"]
plink_species = [s for s in species if s != "may"]
print(plink_species)
datasets = locations + ["all"] #+ species
PAIRS = [f"{a}_{b}" for i,a in enumerate(species) for b in species[i+1:]]
ld_datasets = ["all", "bel", "boc", "hon", "pri", "pue", "uni", "nig", "abe"]

# Rule to generate all dataset-specific files
rule all:
    input:
        expand("byLOC/{loc}.txt", loc=locations),
        expand("bySPC/{spc}.txt", spc=plink_species),
        expand("byLOC/{loc}.vcf.gz", loc=locations),
        expand("bySPC/{spc}.vcf.gz", spc=plink_species),
        expand("byLOC/{loc}_ld_pruned_gtmat.traw", loc=locations),
        expand("bySPC/{spc}_ld_pruned_gtmat.traw", spc=plink_species),
        expand("byLOC/{loc}.ld.pruned.bed", loc=locations),
        expand("bySPC/{spc}.ld.pruned.bed", spc=plink_species),
        expand("byLOC/{loc}.ld.pruned.bim", loc=locations),
        expand("bySPC/{spc}.ld.pruned.bim", spc=plink_species),
        expand("byLOC/{loc}.ld.pruned.fam", loc=locations),
        expand("bySPC/{spc}.ld.pruned.fam", spc=plink_species),
        "byALL/all.agg.ld_pruned_gtmat.traw",
        # Location mode outputs in byLOC/permanova_results/
        expand("byLOC/permanova_results/{dataset}.lm.pairwise.csv", dataset=locations),
        # Species mode outputs in bySPC/permanova_results/
        expand("bySPC/permanova_results/{dataset}.sm.pairwise.csv", dataset=plink_species),
        "byALL/permanova_results/all.sm.pairwise.csv",
        "byALL/permanova_results/all.lm.pairwise.csv",
        # Figure outputs
        expand(
            f"{FIGURES_DIR}/{{fig_name}}",
            fig_name=[
                "Fig2_pairFST.png",
                "FigS11_gFSTviolin.png",
                "FigS12_gLocFST.png",
                "FigS13_gAllsFST.png",
                "FigS14_gSpeFST.png",
                "FigS15_gAllPCA.png",
                "FigS16_gAllVAR.png",
                "FigS17_gLocPCA.png",
                "FigS18_gLocSUP.png",
                "FigS19_gAllPERM.png",
                "FigS20_gLocPERM.png",
                "FigS21_gSpe.png"
            ]
        ),
        f"{FIGURES_DIR}/Fig3_correlations.png",
        expand("newhyb/{dataset}/{pair}/done.txt", dataset=locations, pair=PAIRS),
        expand("newhyb/{dataset}/{pair}/done1.txt", dataset=locations, pair=PAIRS),
        expand(
            f"{FIGURES_DIR}/{{fig_name}}",
            fig_name=[
                "FigS22_newhybrid_bel.png",
                "FigS23_newhybrid_boc.png",
                "FigS24_newhybrid_flk.png",
                "FigS25_newhybrid_hon.png",
                "FigS26_newhybrid_pri.png"
            ]
        ),        "ld/LD.bed",
        expand("ld/{dataset}.bed", dataset=ld_datasets),
        expand("ld/{dataset}.bim", dataset=ld_datasets),
        expand("ld/{dataset}.fam", dataset=ld_datasets),
        expand("ld/{dataset}_filtered.bed", dataset=ld_datasets),
        expand("ld/{dataset}_filtered.bim", dataset=ld_datasets),
        expand("ld/{dataset}_filtered.fam", dataset=ld_datasets),
        expand("ld/{dataset}_global.ld", dataset=ld_datasets),
        expand("ld/{dataset}.regions.snplist", dataset=ld_datasets),
        expand("ld/{dataset}.regions.ld", dataset=ld_datasets),
        expand("ld/{dataset}.LG04_LG12_1.ld", dataset=ld_datasets),
        expand("ld/{dataset}.LG04_LG12_2.ld", dataset=ld_datasets),
        expand("ld/{dataset}.LG12_1_LG12_2.ld", dataset=ld_datasets),
        f"{FIGURES_DIR}/FigS27_LDboxplots.png"


# --- Create directories ---
rule make_dirs:
    output:
        directory("byLOC"),
        directory("bySPC"),
        directory("byALL")
    shell:
        "mkdir -p {output}"


# Generic rule to extract matching samples
rule split_samples_locations:
    input:
        SAMPLES_FILE
    output:
        "byLOC/{dataset}.txt"
    shell:
        "grep -E '[0-9]{{5}}.*{wildcards.dataset}' {input} > {output} || true"


# Reuse same logic for species
rule split_samples_species:
    input:
        SAMPLES_FILE
    output:
        "bySPC/{dataset}.txt"
    shell:
        """
        awk -v sp={wildcards.dataset} '$1 ~ sp {print $1}' {input} > {output}
        """


rule subset_vcf:
    input:
        VCF_FILE = VCF_FILE,
        FILTER_FILE = lambda wildcards: (
            f"byLOC/{wildcards.dataset}.txt"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}.txt"
        )
    output:
        "by{group}/{dataset}.vcf.gz"
    params:
        group = lambda wildcards: "LOC" if wildcards.dataset in locations else "SPC"
    shell:
        r"""
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0

        bcftools view --threads 4 -S {input.FILTER_FILE} -Oz -o {output} {input.VCF_FILE}
        bcftools index {output}
        """


rule plink_processing:
    input:
        VCF = lambda wildcards: (
            f"byLOC/{wildcards.dataset}.vcf.gz"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}.vcf.gz"
        )
    params:
        OUT_DIR = lambda wildcards: (
            "byLOC" if wildcards.dataset in locations else "bySPC"
        )
    output:
        "{OUT_DIR}/{dataset}_ld_pruned_gtmat.traw",
        "{OUT_DIR}/{dataset}.ld.pruned.bed",
        "{OUT_DIR}/{dataset}.ld.pruned.bim",
        "{OUT_DIR}/{dataset}.ld.pruned.fam"
    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        # Create base prefix (remove folder and extensions)
        prefix=$(basename {input.VCF} .vcf.gz)

        # Step 1: Convert to PLINK binary
        plink --vcf {input.VCF} --allow-extra-chr --double-id --make-bed --out $(dirname {input.VCF})/{wildcards.dataset}

        # Step 2: Filter for MAF and missingness
        plink --bfile $(dirname {input.VCF})/{wildcards.dataset} \
              --maf 0.05 --geno 0.05 --allow-extra-chr --double-id --make-bed \
              --out $(dirname {input.VCF})/{wildcards.dataset}.flt

        # Step 3: LD pruning
        plink --bfile $(dirname {input.VCF})/{wildcards.dataset}.flt \
              --indep-pairwise 50 10 0.2 --allow-extra-chr --double-id \
              --out $(dirname {input.VCF})/{wildcards.dataset}.ld

        plink --bfile $(dirname {input.VCF})/{wildcards.dataset}.flt \
              --extract $(dirname {input.VCF})/{wildcards.dataset}.ld.prune.in \
              --allow-extra-chr --double-id --make-bed \
              --out $(dirname {input.VCF})/{wildcards.dataset}.ld.pruned

        # Step 4: Export genotype matrix (transposed)
        plink --bfile $(dirname {input.VCF})/{wildcards.dataset}.ld.pruned \
              --recode A-transpose --allow-extra-chr --double-id \
              --out $(dirname {input.VCF})/{wildcards.dataset}_ld_pruned_gtmat
        """


rule run_permanova:
    input:
        GTMAT = lambda wildcards: (
            f"byLOC/{wildcards.dataset}_ld_pruned_gtmat.traw"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}_ld_pruned_gtmat.traw"
        ),
        GROUPING = lambda wildcards: (
            f"byLOC/{wildcards.dataset}.txt"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}.txt"
        )
    output:
        "{OUTDIR}/{dataset}.{SUFFIX}.pairwise.csv"
    params:
        python_script = PYTHON_SCRIPT,
        OUTDIR = lambda wildcards: (
            f"byLOC/permanova_results/"
            if wildcards.dataset in locations
            else f"bySPC/permanova_results/"
        ),
        MODE_FLAG = lambda wildcards: "-no-s" if wildcards.dataset in locations else "-s",
        SUFFIX = lambda wildcards: (
            "lm" if wildcards.dataset in locations else "sm"
        )
    threads: 1
    shell:
        r"""
        mkdir -p {params.OUTDIR}

        python3 {params.python_script} \
            -i {input.GTMAT} \
            -g {input.GROUPING} \
            -o {params.OUTDIR} \
            {params.MODE_FLAG} \ \
            -n {wildcards.dataset}
        """


rule all_plink:
    input:
        VCF_FILE = VCF_FILE
    output:
        GTMAT = "byALL/all.agg.ld_pruned_gtmat.traw"
    shell:
        r"""
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0
        module load PLINK/v1.9b7.4-x86_64

        # Create index for vcf file
        # bcftools index {input.VCF_FILE}

        # Create base prefix (remove folder and extensions)
        prefix="all"

        # Step 1: Convert to PLINK binary
        plink --vcf {input.VCF_FILE} --allow-extra-chr --double-id --make-bed --out byALL/${{prefix}}

        # Step 2: Filter for MAF and missingness
        plink --bfile byALL/${{prefix}} \
              --maf 0.05 --geno 0.05 --allow-extra-chr --double-id --make-bed \
              --out byALL/${{prefix}}.flt

        # Step 3: LD pruning
        plink --bfile byALL/${{prefix}}.flt \
              --indep-pairwise 50 5 0.1 --double-id --allow-extra-chr \
              --out byALL/${{prefix}}.ld

        plink --bfile byALL/${{prefix}}.flt \
              --extract byALL/${{prefix}}.ld.prune.in \
              --allow-extra-chr --double-id --make-bed \
              --out byALL/${{prefix}}.ld.pruned

        # Step 4: Export genotype matrix (transposed)
        plink --bfile byALL/${{prefix}}.ld.pruned \
              --recode A-transpose --double-id --allow-extra-chr \
              --out byALL/${{prefix}}.agg.ld_pruned_gtmat
        """

rule run_permanova_all:
    input:
        GTMAT = "byALL/all.agg.ld_pruned_gtmat.traw",
        GROUPING = SAMPLES_FILE
    output:
        "byALL/permanova_results/all.lm.pairwise.csv"
        "byALL/permanova_results/all.sm.pairwise.csv"
    params:
        python_script = PYTHON_SCRIPT,
        OUTDIR = "byALL/permanova_results/"
    shell:
        r"""
        python3 {params.python_script} \
            -i {input.GTMAT} \
            -g {input.GROUPING} \
            -o {params.OUTDIR} \
            -no-s \
            -n all


        python3 {params.python_script} \
            -i {input.GTMAT} \
            -g {input.GROUPING} \
            -o {params.OUTDIR} \
            -s \
            -n all
        """


rule multi_fst_windowed_filtered:
    input:
        bed = "byALL/all.flt.bed",
        bim = "byALL/all.flt.bim",
        fam = "byALL/all.flt.fam",
        popu = "byALL/all.pop"
    output:
        fst = "byALL/all.flt.fst.50kb.tsv.gz",
        vcf = "byALL/all.flt.vcf.gz"
    params:
        prefix = "byALL/all.flt",
        window = 50000,
        step = 5000
    shell:
        r"""
        module load PLINK/v1.9b7.4-x86_64
        module load VCFtools/0.1.16-GCC-13.1.0
        module load BCFtools/1.18-GCC-13.1.0

        # ------------------------------------------------------------
        # 1. convert PLINK filtered dataset back to VCF
        # ------------------------------------------------------------
        plink --bfile {params.prefix} \
              --recode vcf bgz \
              --allow-extra-chr \
              --double-id \
              --out {params.prefix}

        bcftools index {params.prefix}.vcf.gz

        # ------------------------------------------------------------
        # 2. multi-pop windowed FST (vcftools = mean pairwise FST)
        # ------------------------------------------------------------
        pixy \
            --vcf {params.prefix}.vcf.gz \
            --populations {input.popu} \
            --window_size {params.window} \
            --n_cores 16 \
            --stats fst dxy \
            --output_folder byALL \
            --output_prefix all.flt \
            --bypass_invariant_check
        """


rule pca_plot:
    input:
        gtmat = lambda wildcards: (
            [f"byLOC/{loc}_ld_pruned_gtmat.traw" for loc in locations] +
            [f"bySPC/{spc}_ld_pruned_gtmat.traw" for spc in plink_species] +
            ["byALL/all.agg.ld_pruned_gtmat.traw"]
        ),
        # PERMANOVA results
        permanova = lambda wildcards: (
            [f"byLOC/permanova_results/{loc}.lm.pairwise.csv" for loc in locations] +
            [f"bySPC/permanova_results/{spc}.sm.pairwise.csv" for spc in plink_species] +
            ["byALL/permanova_results/all.lm.pairwise.csv"] +
            ["byALL/permanova_results/all.sm.pairwise.csv"]
        )
    output:
        f"{FIGURES_DIR}/Fig2_pairFST.png",
        f"{FIGURES_DIR}/FigS11_gFSTviolin.png",
        f"{FIGURES_DIR}/FigS12_gLocFST.png",
        f"{FIGURES_DIR}/FigS13_gAllsFST.png",
        f"{FIGURES_DIR}/FigS14_gSpeFST.png",
        f"{FIGURES_DIR}/FigS15_gAllPCA.png",
        f"{FIGURES_DIR}/FigS16_gAllVAR.png",
        f"{FIGURES_DIR}/FigS17_gLocPCA.png",
        f"{FIGURES_DIR}/FigS18_gLocSUP.png",
        f"{FIGURES_DIR}/FigS19_gAllPERM.png",
        f"{FIGURES_DIR}/FigS20_gLocPERM.png",
        f"{FIGURES_DIR}/FigS21_gSpe.png"
    params:
        base_path = BASE_DIR,
        figure_path = FIGURES_DIR,
        logos_path = f"{BASE_DIR}/metadata/logos_hamlet",
        spec_colors = f"{BASE_DIR}/metadata/species_colors.tsv",
        geo_colors = f"{BASE_DIR}/metadata/locations_colors.tsv"
    threads: 1
    resources:
        mem_mb=64000,
        time="2:00:00"
    shell:
        """
        module load hpc-env/13.1
        module load R/4.3.1-foss-2023a

        Rscript {R_SCRIPT} \
            --base_path {params.base_path} \
            --figure_path {params.figure_path} \
            --logos_path {params.logos_path} \
            --spec_colors {params.spec_colors} \
            --geo_colors {params.geo_colors}
        """


rule corr_plot:
    input:
        gtmat = lambda wildcards: (
            [f"byLOC/{loc}_ld_pruned_gtmat.traw" for loc in locations] +
            ["byALL/all.agg.ld_pruned_gtmat.traw"]
        )
    output:
        f"{FIGURES_DIR}/Fig3_correlations.png"
    params:
        R_code = os.path.join(SCRIPTS_DIR, "R", "Fig3.R"),
        base_path = BASE_DIR,
        figure_path = FIGURES_DIR,
        path_phenotypes = PHENO_DIR,
        logos_path = f"{BASE_DIR}/metadata/logos_hamlet",
        spec_colors = f"{BASE_DIR}/metadata/species_colors.tsv",
        geo_colors = f"{BASE_DIR}/metadata/locations_colors.tsv"
    threads: 1
    resources:
        mem_mb=100000,
        time="2:00:00"
    shell:
        """
        module load hpc-env/13.1
        module load R/4.3.1-foss-2023a

        Rscript {params.R_code} \
            --base_path {params.base_path} \
            --figure_path {params.figure_path} \
            --path_phenotypes {params.path_phenotypes} \
            --logos_path {params.logos_path} \
            --spec_colors {params.spec_colors} \
            --geo_colors {params.geo_colors}
        """


rule newhyb_from_fst:
    input:
        VCF_FILE = VCF_FILE,
        samples="byLOC/{dataset}.txt"
    output:
        "newhyb/{dataset}/{pair}/done.txt"
    params:
        sp1=lambda wc: wc.pair.split("_")[0],
        sp2=lambda wc: wc.pair.split("_")[1]
    resources:
        mem_mb=10000,
        runtime=720
    shell:
        """
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0
        module load PLINK/v1.9b7.4-x86_64
        module load VCFtools/0.1.16-GCC-13.1.0
        module load R/4.3.1-foss-2023a

        set -x

        sp1={params.sp1}
        sp2={params.sp2}

        outdir=newhyb/{wildcards.dataset}/{wildcards.pair}
        # mkdir -p $outdir/nh_input

        # count individuals
        n1=$(awk -v sp=${{sp1}} -v loc={wildcards.dataset} '$1 ~ sp && $1 ~ loc {{c++}} END {{print c+0}}' byLOC/{wildcards.dataset}.txt)
        n2=$(awk -v sp=${{sp2}} -v loc={wildcards.dataset} '$1 ~ sp && $1 ~ loc {{c++}} END {{print c+0}}' byLOC/{wildcards.dataset}.txt)

        if [ ${{n1}} -lt 5 ] || [ ${{n2}} -lt 5 ]; then
            echo "Skipping ${{sp1}}-${{sp2}} (low N)"
            touch {output}
            exit 0
        fi

        echo "Running ${{sp1}} vs ${{sp2}}"
        
        # create keep file (plink format: FID IID)
        awk -v s1=${{sp1}} -v s2=${{sp2}} -v loc={wildcards.dataset} \
            '($1 ~ s1 && $1 ~ loc) || ($1 ~ s2 && $1 ~ loc) {{print $1}}' \
            {input.samples} > $outdir/keep.txt
        
        # subset for pairs from overall dataset
        bcftools view --threads 4 -S $outdir/keep.txt -Oz -o $outdir/pair.vcf.gz {input.VCF_FILE}

        #convert to binary
        plink --vcf $outdir/pair.vcf.gz --allow-extra-chr --double-id --make-bed --out $outdir/pair

        # light filtering on the subset
        plink \
            --bfile $outdir/pair \
            --geno 0.05 \
            --maf 0.01 \
            --allow-extra-chr \
            --recode vcf-iid bgz \
            --out $outdir/data

        # compress VCF
        bcftools index $outdir/data.vcf.gz

        # create pop file for both species in the pair
        awk -v s=${{sp1}} '$1 ~ s {{print $1}}' $outdir/keep.txt > $outdir/pop1.txt
        awk -v s=${{sp2}} '$1 ~ s {{print $1}}' $outdir/keep.txt > $outdir/pop2.txt

        # compute fsts/snps for the species pair
        vcftools --gzvcf $outdir/data.vcf.gz \
                 --weir-fst-pop $outdir/pop1.txt \
                 --weir-fst-pop $outdir/pop2.txt \
                 --out $outdir/fst

        # tail -n +2 $outdir/fst.weir.fst | sort -k3,3gr | head -n 800 | cut -f1,2 | shuf -n 80 > $outdir/snps.txt.tmp
        
        # 1. Remove header
        tail -n +2 $outdir/fst.weir.fst > $outdir/fst.noheader.txt

        # 2. Sort by FST (column 3)
        sort -k3,3gr $outdir/fst.noheader.txt > $outdir/fst.sorted.txt

        # 3. Take top 800 SNPs
        head -n 800 $outdir/fst.sorted.txt > $outdir/fst.top800.txt

        # 4. Keep only CHROM and POS
        cut -f1,2 $outdir/fst.top800.txt > $outdir/fst.top800.pos.txt

        # 5. Randomly sample 80 SNPs
        shuf $outdir/fst.top800.pos.txt | head -n 80 > $outdir/snps.txt
        
        # mv $outdir/snps.txt.tmp $outdir/snps.txt
        
        touch {output}
        """

rule newhyb_from_snps:
    input:
        VCF_FILE = VCF_FILE,
        snps="newhyb/{dataset}/{pair}/done.txt"
    output:
        "newhyb/{dataset}/{pair}/done1.txt"
    params:
        sp1=lambda wc: wc.pair.split("_")[0],
        sp2=lambda wc: wc.pair.split("_")[1]
    resources:
        mem_mb=10000,
        runtime=720
    shell:
        """
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0
        module load R/4.3.1-foss-2023a

        set -x

        sp1={params.sp1}
        sp2={params.sp2}

        outdir=newhyb/{wildcards.dataset}/{wildcards.pair}/
        mkdir -p $outdir/nh_input/

        # count individuals
        n1=$(awk -v sp=${{sp1}} -v loc={wildcards.dataset} '$1 ~ sp && $1 ~ loc {{c++}} END {{print c+0}}' byLOC/{wildcards.dataset}.txt)
        n2=$(awk -v sp=${{sp2}} -v loc={wildcards.dataset} '$1 ~ sp && $1 ~ loc {{c++}} END {{print c+0}}' byLOC/{wildcards.dataset}.txt)

        if [ ${{n1}} -lt 5 ] || [ ${{n2}} -lt 5 ]; then
            echo "Skipping ${{sp1}}-${{sp2}} (low N)"
            touch {output}
            exit 0
        fi

        echo "Running ${{sp1}} vs ${{sp2}}"       
        
        bcftools view -R $outdir/snps.txt $outdir/data.vcf.gz -Oz -o $outdir/data.80subset.vcf.gz
        bcftools index $outdir/data.80subset.vcf.gz

        nind_vcf=$(bcftools query -l $outdir/data.80subset.vcf.gz | wc -l)

        if [ "$nind_vcf" -eq 0 ]; then
            echo "No individuals left after filtering for ${{sp1}}-${{sp2}}"
            touch {output}
            exit 0
        fi

        # genotype conversion
        bcftools query -f '%CHROM:%POS[\\t%GT]\\n' $outdir/data.80subset.vcf.gz > $outdir/tmp.geno

        # count
        nloc=$(wc -l < $outdir/tmp.geno)
        nind=$(head -n1 $outdir/tmp.geno | awk '{{print NF-1}}')
                    
        # header
        echo "NumIndivs ${{nind}}" > $outdir/nh_input/input.txt
        echo "NumLoci ${{nloc}}" >> $outdir/nh_input/input.txt
        echo "Digits 1" >> $outdir/nh_input/input.txt
        echo "Format Lumped" >> $outdir/nh_input/input.txt
                    
        # locus names
        awk '{{printf "SNP_%d ", NR}} END {{printf "\\n"}}' $outdir/tmp.geno | \
        sed '1s/^/LocusNames /' >> $outdir/nh_input/input.txt
        
        # transpose + recode
        awk '{{
            for(i=2; i<=NF; i++) {{
                g=$i;
                if(g=="0/0") v="11";
                else if(g=="0/1" || g=="1/0") v="12";
                else if(g=="1/1") v="22";
                else v="0";
                matrix[i-1,NR]=v;
                if(i-1 > max_ind) max_ind=i-1;
            }}
        }}
        END {{
            for(i=1; i<=max_ind; i++) {{
                printf "%d", i;
                for(j=1; j<=NR; j++) {{
                    printf " %s", matrix[i,j];
                }}
                printf "\\n";
            }}
        }}' $outdir/tmp.geno >> $outdir/nh_input/input.txt


        bcftools query -l $outdir/data.80subset.vcf.gz > $outdir/nh_input/individuals.txt


        # run NewHybrids
        Rscript {SCRIPTS_DIR}/R/newhybrids.R $outdir/nh_input/

        touch {output}
        """


rule plot_newhybrids:
    input:
        expand("newhyb/{dataset}/{pair}/done1.txt",
               dataset=locations,
               pair=PAIRS)
    output:
        f"{FIGURES_DIR}/FigS22_newhybrid_bel.png",
        f"{FIGURES_DIR}/FigS23_newhybrid_boc.png",
        f"{FIGURES_DIR}/FigS24_newhybrid_flk.png",
        f"{FIGURES_DIR}/FigS25_newhybrid_hon.png",
        f"{FIGURES_DIR}/FigS26_newhybrid_pri.png"
    params:
        base_dir = BASE_DIR,
        fig_dir = FIGURES_DIR
    shell:
        r"""
        module load R/4.3.1-foss-2023a
        Rscript {SCRIPTS_DIR}/R/FigS22-26.R {params.base_dir} {params.fig_dir}
        """


rule make_ld_bed:
    input:
        GXP_FILE
    output:
        "ld/LD.bed"
    params:
        flank=100000
    shell:
        r"""
        mkdir -p ld/

        awk -v flank={params.flank} 'BEGIN {{OFS="\t"}}
        $1 == "CHROM" {{next}}   # skip header or dummy row
        {{
            start=$2-flank;
            if (start < 1) start=1;
            end=$2+flank;
            print $1, start, end, $1"_"$2
        }}' {input} > {output}
        """


rule vcf_to_plink:
    wildcard_constraints:
        dataset="all|bel|boc|hon|pri|pue|uni|nig|abe"
    input:
        vcf=lambda wc: (
            VCF_FILE if wc.dataset == "all"
            else f"byLOC/{wc.dataset}.vcf.gz" if wc.dataset in locations
            else f"bySPC/{wc.dataset}.vcf.gz"
        ),
    output:
        bed="ld/{dataset}.bed",
        bim="ld/{dataset}.bim",
        fam="ld/{dataset}.fam"
    params:
        prefix="ld/{dataset}"
    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        plink --vcf {input.vcf} \
              --double-id \
              --allow-extra-chr \
              --make-bed \
              --out {params.prefix}
        """


rule ld_filter:
    wildcard_constraints:
        dataset="all|bel|boc|hon|pri|pue|uni|nig|abe"
    input:
        bed="ld/{dataset}.bed",
        bim="ld/{dataset}.bim",
        fam="ld/{dataset}.fam"
    output:
        bed="ld/{dataset}_filtered.bed",
        bim="ld/{dataset}_filtered.bim",
        fam="ld/{dataset}_filtered.fam"
    params:    
        prefix="ld/{dataset}"
    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        plink --bfile {params.prefix} \
              --allow-extra-chr \
              --set-missing-var-ids @:# \
              --maf 0.05 \
              --geno 0.05 \
              --make-bed \
              --out {params.prefix}_filtered
        """

rule ld_global:
    wildcard_constraints:
        dataset="all|bel|boc|hon|pri|pue|uni|nig|abe"
    input:
        bed="ld/{dataset}_filtered.bed",
        bim="ld/{dataset}_filtered.bim",
        fam="ld/{dataset}_filtered.fam"
    output:
        ld="ld/{dataset}_global.ld"
    params:
        prefix="ld/{dataset}"
    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        # enforce spacing
        plink --bfile {params.prefix}_filtered \
              --allow-extra-chr \
              --bp-space 1000000 \
              --make-bed \
              --set-missing-var-ids @:# \
              --out {params.prefix}_1Mb

        # sample 500 SNPs
        cut -f2 {params.prefix}_1Mb.bim | shuf | head -n 500 > {params.prefix}_global.snps

        # compute LD
        plink --bfile {params.prefix}_1Mb \
              --extract {params.prefix}_global.snps \
              --allow-extra-chr \
              --r2 square \
              --out {params.prefix}_global
        """


rule region_snps:
    wildcard_constraints:
        dataset="all|bel|boc|hon|pri|pue|uni|nig|abe"

    input:
        bed="ld/{dataset}_filtered.bed",
        bim="ld/{dataset}_filtered.bim",
        fam="ld/{dataset}_filtered.fam",
        regions="ld/LD.bed"
    output:
        snps="ld/{dataset}.regions.snplist"
    params:
        prefix="ld/{dataset}"
    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        plink --bfile {params.prefix}_filtered \
              --extract range {input.regions} \
              --allow-extra-chr \
              --set-missing-var-ids @:# \
              --write-snplist \
              --out {params.prefix}.regions
        """


rule ld_regions_all:
    wildcard_constraints:
        dataset="all|bel|boc|hon|pri|pue|uni|nig|abe"

    input:
        bed="ld/{dataset}_filtered.bed",
        bim="ld/{dataset}_filtered.bim",
        fam="ld/{dataset}_filtered.fam",
        snps="ld/{dataset}.regions.snplist"

    output:
        ld="ld/{dataset}.regions.ld"

    params:
        prefix="ld/{dataset}"

    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        plink --bfile {params.prefix}_filtered \
              --extract {input.snps} \
              --allow-extra-chr \
              --r2 inter-chr \
              --ld-window-r2 0 \
              --out {params.prefix}.regions
        """


rule split_region_ld_full:
    input:
        bed="ld/LD.bed",
        ld="ld/{dataset}.regions.ld"
    output:
        lg04_lg12_1="ld/{dataset}.LG04_LG12_1.ld",
        lg04_lg12_2="ld/{dataset}.LG04_LG12_2.ld",
        lg12_1_lg12_2="ld/{dataset}.LG12_1_LG12_2.ld"
    params:
        prefix="ld/{dataset}"
    shell:
        r"""
        set -euo pipefail

        ############################
        # 1. build regions table
        ############################
        awk 'NR==FNR {{
            chr[$4]=$1;
            start[$4]=$2;
            end[$4]=$3;
            next
        }}
        {{
            split($3,a,":"); chrA=a[1]; posA=a[2]
            split($6,b,":"); chrB=b[1]; posB=b[2]

            regA="NA"; regB="NA"

            for (r in chr) {{
                if (chrA==chr[r] && posA>=start[r] && posA<=end[r]) regA=r
                if (chrB==chr[r] && posB>=start[r] && posB<=end[r]) regB=r
            }}

            if (regA!="NA" && regB!="NA")
                print regA, regB, $0

        }}' {input.bed} {input.ld} > {params.prefix}.tmp.annotated.ld

        ############################
        # 2. split comparisons
        ############################

        awk '
        {{
            a=$1; b=$2;

            if (a > b) {{
                tmp=a; a=b; b=tmp;
            }}

            if ((a ~ /^LG04/ && b=="LG12_20232954") ||
                (a=="LG12_20232954" && b ~ /^LG04/))
                print >> "{output.lg04_lg12_1}"

            else if ((a ~ /^LG04/ && b=="LG12_22227968") ||
                     (a=="LG12_22227968" && b ~ /^LG04/))
                print >> "{output.lg04_lg12_2}"

            else if ((a=="LG12_20232954" && b=="LG12_22227968") ||
                     (a=="LG12_22227968" && b=="LG12_20232954"))
                print >> "{output.lg12_1_lg12_2}"
        }}' {params.prefix}.tmp.annotated.ld

        rm -f {params.prefix}.tmp.annotated.ld
        """

rule plot_ld:
    input:
        expand("ld/{dataset}_global.ld", dataset=ld_datasets),
        expand("ld/{dataset}.LG04_LG12_1.ld", dataset=ld_datasets),
        expand("ld/{dataset}.LG04_LG12_2.ld", dataset=ld_datasets),
        expand("ld/{dataset}.LG12_1_LG12_2.ld", dataset=ld_datasets)
    output:
        f"{FIGURES_DIR}/FigS27_LDboxplots.png"
    params:
        base_dir = BASE_DIR,
        fig_dir = FIGURES_DIR
    shell:
        r"""
        module load R/4.3.1-foss-2023a
        Rscript {SCRIPTS_DIR}/R/FigS27.R {params.base_dir} {params.fig_dir}
        """