#!/usr/bin/python 
# by: Floriane Coulmance: 31.10.2025 

import os

BASE_DIR="/fs/dss/work/doau0129/hamlet_pheno"  # hamlet_pheno/
GENO_DIR=os.path.join(BASE_DIR, "2_popgen")
SAMPLES_FILE=os.path.join(BASE_DIR, "metadata/geno_names.txt")
VCF_FILE=os.path.join(BASE_DIR, "phyps2e_m2.vcf.gz")
GXP_FILE=os.path.join(BASE_DIR, "metadata/color_gxp_peaks.txt")


FIGURES_DIR = os.path.join(BASE_DIR, "figures")
SCRIPTS_DIR = os.path.join(BASE_DIR, "scripts")
PYTHON_SCRIPT = os.path.join(SCRIPTS_DIR, "python", "permanova.py")
R_SCRIPT = os.path.join(SCRIPTS_DIR, "R", "Fig3-4_S11-S18.R")
SPID_SCRIPT = os.path.join(SCRIPTS_DIR, "sh", "vcf2nh.spid")


# # List of datasets
# genotyping_params = [
#     # Per location, all species
#     {"dataset": "arc"},
#     {"dataset": "bar"},
#     {"dataset": "bel"},
#     {"dataset": "boc"},
#     {"dataset": "flk"},
#     {"dataset": "gun"},
#     {"dataset": "hon"},
#     {"dataset": "liz"},
#     {"dataset": "pri"},
#     {"dataset": "qui"},
#     # Overall location (all species combined)
#     {"dataset": "all"},
#     # Specific species (geo_name = all)
#     {"dataset": "abe"},
#     {"dataset": "aff"},
#     {"dataset": "atl"},
#     {"dataset": "chl"},
#     {"dataset": "gem"},
#     {"dataset": "gum"},
#     {"dataset": "gut"},
#     {"dataset": "ind"},
#     {"dataset": "nig"},
#     {"dataset": "pue"},
#     {"dataset": "ran"},
#     {"dataset": "tan"},
#     {"dataset": "uni"},
#     {"dataset": "may"},

# ]

# Separate datasets into "location" and "species" groups
locations = ["arc","bar","bel","boc","flk","gun","hon","liz","pri","qui"]
species = ["abe","aff","atl","chl","gem","gum","gut","ind","nig","pue","ran","tan","uni","may"]
plink_species = [s for s in species if s != "may"]
print(plink_species)
datasets = locations + ["all"] #+ species
PAIRS = [f"{a}_{b}" for i,a in enumerate(species) for b in species[i+1:]]
ld_datasets = ["all", "bel", "boc", "hon", "pri", "pue", "uni", "nig", "abe"]

# Rule to generate all dataset-specific files
rule all:
    input:
        expand("byLOC/{loc}.txt", loc=locations),
        expand("bySPC/{spc}.txt", spc=plink_species),
        expand("byLOC/{loc}.vcf.gz", loc=locations),
        expand("bySPC/{spc}.vcf.gz", spc=plink_species),
        expand("byLOC/{loc}_ld_pruned_gtmat.traw", loc=locations),
        expand("bySPC/{spc}_ld_pruned_gtmat.traw", spc=plink_species),
        "byALL/all.agg.ld_pruned_gtmat.traw",
        # Location mode outputs in byLOC/permanova_results/
        expand("byLOC/permanova_results/{dataset}.lm.pairwise.csv", dataset=locations),
        # Species mode outputs in bySPC/permanova_results/
        expand("bySPC/permanova_results/{dataset}.sm.pairwise.csv", dataset=plink_species),
        "byALL/permanova_results/all.sm.pairwise.csv",
        "byALL/permanova_results/all.lm.pairwise.csv",
        # Figure outputs
        expand(
            f"{FIGURES_DIR}/{{fig_name}}",
            fig_name=[
                "Fig3_gAllPCA.png",
                "Fig4_gLocPCA.png",
                "FigS11_gAllVAR.png",
                "FigS12_gLocSUP.png",
                "FigS13_gLocPERM.png",
                "FigS14_gAllPERM.png",
                "FigS15_gSpe.png",
                "FigS16_gFSTviolin.png",
                "FigS17_gLocFST.png",
                "FigS18_gAllsFST.png",
                "FigS19_gSpeFST.png"
            ]
        ),
        expand("newhyb/{dataset}/{pair}/done.txt", dataset=locations, pair=PAIRS),
        f"{FIGURES_DIR}/FigS20_newhybrid.png",
        "ld/LD.bed",
        expand("ld/{dataset}_ILD.ld", dataset=ld_datasets),
        expand("ld/{dataset}_LG12_12.ld", dataset=ld_datasets)




# --- Create directories ---
rule make_dirs:
    output:
        directory("byLOC"),
        directory("bySPC"),
        directory("byALL")
    shell:
        "mkdir -p {output}"


# Generic rule to extract matching samples
rule split_samples_locations:
    input:
        SAMPLES_FILE
    output:
        "byLOC/{dataset}.txt"
    shell:
        "grep -E '[0-9]{{5}}.*{wildcards.dataset}' {input} > {output} || true"


# Reuse same logic for species
rule split_samples_species:
    input:
        SAMPLES_FILE
    output:
        "bySPC/{dataset}.txt"
    shell:
        "grep -E '[0-9]{{5}}.*{wildcards.dataset}' {input} > {output} || true"


rule subset_vcf:
    input:
        VCF_FILE = VCF_FILE,
        FILTER_FILE = lambda wildcards: (
            f"byLOC/{wildcards.dataset}.txt"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}.txt"
        )
    output:
        "by{group}/{dataset}.vcf.gz"
    params:
        group = lambda wildcards: "LOC" if wildcards.dataset in locations else "SPC"
    shell:
        r"""
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0

        bcftools view --threads 4 -S {input.FILTER_FILE} -Oz -o {output} {input.VCF_FILE}
        bcftools index {output}
        """


rule plink_processing:
    input:
        VCF = lambda wildcards: (
            f"byLOC/{wildcards.dataset}.vcf.gz"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}.vcf.gz"
        )
    params:
        OUT_DIR = lambda wildcards: (
            "byLOC" if wildcards.dataset in locations else "bySPC"
        )
    output:
        "{OUT_DIR}/{dataset}_ld_pruned_gtmat.traw"
    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        # Create base prefix (remove folder and extensions)
        prefix=$(basename {input.VCF} .vcf.gz)

        # Step 1: Convert to PLINK binary
        plink --vcf {input.VCF} --allow-extra-chr --make-bed --out $(dirname {input.VCF})/{wildcards.dataset}

        # Step 2: Filter for MAF and missingness
        plink --bfile $(dirname {input.VCF})/{wildcards.dataset} \
              --maf 0.05 --geno 0.05 --allow-extra-chr --make-bed \
              --out $(dirname {input.VCF})/{wildcards.dataset}.flt

        # Step 3: LD pruning
        plink --bfile $(dirname {input.VCF})/{wildcards.dataset}.flt \
              --indep-pairwise 50 10 0.2 --allow-extra-chr \
              --out $(dirname {input.VCF})/{wildcards.dataset}.ld

        plink --bfile $(dirname {input.VCF})/{wildcards.dataset}.flt \
              --extract $(dirname {input.VCF})/{wildcards.dataset}.ld.prune.in \
              --allow-extra-chr --make-bed \
              --out $(dirname {input.VCF})/{wildcards.dataset}.ld.pruned

        # Step 4: Export genotype matrix (transposed)
        plink --bfile $(dirname {input.VCF})/{wildcards.dataset}.ld.pruned \
              --recode A-transpose --allow-extra-chr \
              --out $(dirname {input.VCF})/{wildcards.dataset}_ld_pruned_gtmat
        """


rule run_permanova:
    input:
        GTMAT = lambda wildcards: (
            f"byLOC/{wildcards.dataset}_ld_pruned_gtmat.traw"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}_ld_pruned_gtmat.traw"
        ),
        GROUPING = lambda wildcards: (
            f"byLOC/{wildcards.dataset}.txt"
            if wildcards.dataset in locations
            else f"bySPC/{wildcards.dataset}.txt"
        )
    output:
        "{OUTDIR}/{dataset}.{SUFFIX}.pairwise.csv"
    params:
        python_script = PYTHON_SCRIPT,
        OUTDIR = lambda wildcards: (
            f"byLOC/permanova_results/"
            if wildcards.dataset in locations
            else f"bySPC/permanova_results/"
        ),
        MODE_FLAG = lambda wildcards: "-no-s" if wildcards.dataset in locations else "-s",
        SUFFIX = lambda wildcards: (
            "lm" if wildcards.dataset in locations else "sm"
        )
    threads: 1
    shell:
        r"""
        mkdir -p {params.OUTDIR}

        python3 {params.python_script} \
            -i {input.GTMAT} \
            -g {input.GROUPING} \
            -o {params.OUTDIR} \
            {params.MODE_FLAG} \ \
            -n {wildcards.dataset}
        """


rule all_plink:
    input:
        VCF_FILE = VCF_FILE
    output:
        GTMAT = "byALL/all.agg.ld_pruned_gtmat.traw"
    shell:
        r"""
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0
        module load PLINK/v1.9b7.4-x86_64

        # Create index for vcf file
        bcftools index {input.VCF_FILE}

        # Create base prefix (remove folder and extensions)
        prefix="all"

        # Step 1: Convert to PLINK binary
        plink --vcf {input.VCF_FILE} --allow-extra-chr --make-bed --out byALL/${{prefix}}

        # Step 2: Filter for MAF and missingness
        plink --bfile byALL/${{prefix}} \
              --maf 0.05 --geno 0.05 --allow-extra-chr --make-bed \
              --out byALL/${{prefix}}.flt

        # Step 3: LD pruning
        plink --bfile byALL/${{prefix}}.flt \
              --indep-pairwise 50 5 0.1 --allow-extra-chr \
              --out byALL/${{prefix}}.ld

        plink --bfile byALL/${{prefix}}.flt \
              --extract byALL/${{prefix}}.ld.prune.in \
              --allow-extra-chr --make-bed \
              --out byALL/${{prefix}}.ld.pruned

        # Step 4: Export genotype matrix (transposed)
        plink --bfile byALL/${{prefix}}.ld.pruned \
              --recode A-transpose --allow-extra-chr \
              --out byALL/${{prefix}}.agg.ld_pruned_gtmat
        """

rule run_permanova_all:
    input:
        GTMAT = "byALL/all.agg.ld_pruned_gtmat.traw",
        GROUPING = SAMPLES_FILE
    output:
        "byALL/permanova_results/all.lm.pairwise.csv"
        "byALL/permanova_results/all.sm.pairwise.csv"
    params:
        python_script = PYTHON_SCRIPT,
        OUTDIR = "byALL/permanova_results/"
    shell:
        r"""
        python3 {params.python_script} \
            -i {input.GTMAT} \
            -g {input.GROUPING} \
            -o {params.OUTDIR} \
            -no-s \
            -n all


        python3 {params.python_script} \
            -i {input.GTMAT} \
            -g {input.GROUPING} \
            -o {params.OUTDIR} \
            -s \
            -n all
        """


rule pca_plot:
    input:
        gtmat = lambda wildcards: (
            [f"byLOC/{loc}_ld_pruned_gtmat.traw" for loc in locations] +
            [f"bySPC/{spc}_ld_pruned_gtmat.traw" for spc in plink_species] +
            ["byALL/all.agg.ld_pruned_gtmat.traw"]
        ),
        # PERMANOVA results
        permanova = lambda wildcards: (
            [f"byLOC/permanova_results/{loc}.lm.pairwise.csv" for loc in locations] +
            [f"bySPC/permanova_results/{spc}.sm.pairwise.csv" for spc in plink_species] +
            ["byALL/permanova_results/all.lm.pairwise.csv"] +
            ["byALL/permanova_results/all.sm.pairwise.csv"]
        )
    output:
        f"{FIGURES_DIR}/Fig3_gAllPCA.png",
        f"{FIGURES_DIR}/Fig4_gLocPCA.png",
        f"{FIGURES_DIR}/FigS11_gAllVAR.png",
        f"{FIGURES_DIR}/FigS12_gLocSUP.png",
        f"{FIGURES_DIR}/FigS13_gLocPERM.png",
        f"{FIGURES_DIR}/FigS14_gAllPERM.png",
        f"{FIGURES_DIR}/FigS15_gSpe.png",
        f"{FIGURES_DIR}/FigS16_gFSTviolin.png",
        f"{FIGURES_DIR}/FigS17_gLocFST.png",
        f"{FIGURES_DIR}/FigS18_gAllsFST.png",
        f"{FIGURES_DIR}/FigS19_gSpeFST.png"
    params:
        base_path = BASE_DIR,
        figure_path = FIGURES_DIR,
        logos_path = f"{BASE_DIR}/metadata/logos_hamlet",
        spec_colors = f"{BASE_DIR}/metadata/species_colors.tsv",
        geo_colors = f"{BASE_DIR}/metadata/locations_colors.tsv"
    threads: 1
    resources:
        mem_mb=2000,
        time="2:00:00"
    shell:
        """
        module load hpc-env/13.1
        module load R/4.3.1-foss-2023a

        Rscript {R_SCRIPT} \
            --base_path {params.base_path} \
            --figure_path {params.figure_path} \
            --logos_path {params.logos_path} \
            --spec_colors {params.spec_colors} \
            --geo_colors {params.geo_colors}
        """


rule newhyb_from_pruned:
    input:
        bed="byLOC/{dataset}.ld.pruned.bed",
        bim="byLOC/{dataset}.ld.pruned.bim",
        fam="byLOC/{dataset}.ld.pruned.fam",
        samples="byLOC/{dataset}.txt"
    output:
        "newhyb/{dataset}/{pair}/done.txt"
    params:
        sp1=lambda wc: wc.pair.split("_")[0],
        sp2=lambda wc: wc.pair.split("_")[1]
    resources:
        mem_mb=10000,
        runtime=720
    shell:
        """
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0
        module load PLINK/v1.9b7.4-x86_64
        module load R/4.3.1-foss-2023a

        set -x

        sp1={params.sp1}
        sp2={params.sp2}

        outdir=newhyb/{wildcards.dataset}/{wildcards.pair}
        mkdir -p $outdir/nh_input

        # count individuals
        # n1=$(grep ${{sp1}}{wildcards.dataset} {input.samples} | wc -l || true)
        # n2=$(grep ${{sp2}}{wildcards.dataset} {input.samples} | wc -l || true)

        n1=$(awk -v sp=${{sp1}} -v loc={wildcards.dataset} '$1 ~ sp && $1 ~ loc {{c++}} END {{print c+0}}' byLOC/{wildcards.dataset}.txt)
        n2=$(awk -v sp=${{sp2}} -v loc={wildcards.dataset} '$1 ~ sp && $1 ~ loc {{c++}} END {{print c+0}}' byLOC/{wildcards.dataset}.txt)

        if [ ${{n1}} -lt 5 ] || [ ${{n2}} -lt 5 ]; then
            echo "Skipping ${{sp1}}-${{sp2}} (low N)"
            touch {output}
            exit 0
        fi

        echo "Running ${{sp1}} vs ${{sp2}}"
        
        # create keep file (plink format: FID IID)
        awk -v s1=${{sp1}} -v s2=${{sp2}} -v loc={wildcards.dataset} \
            '($1 ~ s1 && $1 ~ loc) || ($1 ~ s2 && $1 ~ loc) {{print $1, $1}}' \
            {input.samples} > $outdir/keep.txt

        # subset PLINK dataset
        plink \
            --bfile byLOC/{wildcards.dataset}.ld.pruned \
            --keep $outdir/keep.txt \
            --allow-extra-chr \
            --recode vcf-iid bgz \
            --out $outdir/data

        # compress VCF
        bcftools index $outdir/data.vcf.gz

        # subsample SNPs (fast + simple)
        bcftools view -H $outdir/data.vcf.gz | shuf -n 200 | cut -f1,2 > $outdir/snps.txt

        bcftools view -R $outdir/snps.txt $outdir/data.vcf.gz -Oz -o $outdir/data.subset.vcf.gz
        bcftools index $outdir/data.subset.vcf.gz

        nind_vcf=$(bcftools query -l $outdir/data.subset.vcf.gz | wc -l)

        if [ "$nind_vcf" -eq 0 ]; then
            echo "No individuals left after filtering for ${{sp1}}-${{sp2}}"
            touch {output}
            exit 0
        fi

        # count SNPs: can comment since we thin the data
        # nsnps=$(bcftools view -H $outdir/data.vcf.gz | wc -l)
        # echo -e "{wildcards.dataset}\t${{sp1}}\t${{sp2}}\t${{nsnps}}" >> newhyb/snp_counts.tsv

        # genotype conversion
        bcftools query -f '%CHROM:%POS[\\t%GT]\\n' $outdir/data.subset.vcf.gz > $outdir/tmp.geno

        # count
        nloc=$(wc -l < $outdir/tmp.geno)
        nind=$(head -n1 $outdir/tmp.geno | awk '{{print NF-1}}')
                    
        # header
        echo "NumIndivs ${{nind}}" > $outdir/nh_input/input.txt
        echo "NumLoci ${{nloc}}" >> $outdir/nh_input/input.txt
        echo "Digits 1" >> $outdir/nh_input/input.txt
        echo "Format Lumped" >> $outdir/nh_input/input.txt
                    
        # locus names
        awk '{{printf "SNP_%d ", NR}} END {{printf "\\n"}}' $outdir/tmp.geno | \
        sed '1s/^/LocusNames /' >> $outdir/nh_input/input.txt
        
        # transpose + recode
        awk '{{
            for(i=2; i<=NF; i++) {{
                g=$i;
                if(g=="0/0") v="11";
                else if(g=="0/1" || g=="1/0") v="12";
                else if(g=="1/1") v="22";
                else v="0";
                matrix[i-1,NR]=v;
                if(i-1 > max_ind) max_ind=i-1;
            }}
        }}
        END {{
            for(i=1; i<=max_ind; i++) {{
                printf "%d", i;
                for(j=1; j<=NR; j++) {{
                    printf " %s", matrix[i,j];
                }}
                printf "\\n";
            }}
        }}' $outdir/tmp.geno >> $outdir/nh_input/input.txt


        bcftools query -l $outdir/data.subset.vcf.gz > $outdir/nh_input/individuals.txt


        # run NewHybrids
        Rscript {SCRIPTS_DIR}/R/newhybrids.R $outdir/nh_input/

        touch {output}
        """


rule plot_newhybrids:
    input:
        expand("newhyb/{dataset}/{pair}/done.txt",
               dataset=locations,
               pair=PAIRS)
    output:
        fig = f"{FIGURES_DIR}/FigS20_newhybrid.png"
    params:
        base_dir = BASE_DIR,
        fig_dir = FIGURES_DIR
    shell:
        r"""
        module load R/4.3.1-foss-2023a
        Rscript {SCRIPTS_DIR}/R/FigS20.R {params.base_dir} {params.fig_dir}
        """


rule make_ld_bed:
    input:
        GXP_FILE
    output:
        "ld/LD.bed"
    params:
        flank=250000
    shell:
        r"""
        awk -v flank={params.flank} 'BEGIN {{OFS="\t"}}
        $1 == "CHROM" {{next}}   # skip header or dummy row
        {{
            start=$2-flank;
            if (start < 1) start=1;
            end=$2+flank;
            print $1, start, end, $1"_"$2
        }}' {input} > {output}
        """


rule compute_ild:
    input:
        vcf=lambda wc: (
            VCF_FILE if wc.dataset == "all"
            else f"byLOC/{wc.dataset}.vcf.gz" if wc.dataset in locations
            else f"bySPC/{wc.dataset}.vcf.gz"
        ),
        bed="ld/LD.bed"
    output:
        "ld/{dataset}_ILD.ld"
    params:
        tmp_prefix="ld/{dataset}_plink"
    shell:
        r"""
        module load hpc-env/13.1
        module load PLINK/v1.9b7.4-x86_64

        # 1. Convert VCF → PLINK
        plink --vcf {input.vcf} \
              --double-id \
              --allow-extra-chr \
              --make-bed \
              --out {params.tmp_prefix}

        # 2. Compute LD only in regions of interest
        plink --bfile {params.tmp_prefix} \
              --allow-extra-chr \
              --extract range {input.bed} \
              --r2 \
              --ld-window-kb 1000 \
              --ld-window 99999 \
              --ld-window-r2 0 \
              --out ld/{wildcards.dataset}_ILD
        """

rule ld_LG12_between:
    input:
        vcf=lambda wc: (
            VCF_FILE if wc.dataset == "all"
            else f"byLOC/{wc.dataset}.vcf.gz" if wc.dataset in locations
            else f"bySPC/{wc.dataset}.vcf.gz"
        )
    output:
        "ld/{dataset}_LG12_12.ld"
    params:
        tmp_vcf="ld/{dataset}_LG12.vcf.gz",
        tmp_prefix="ld/{dataset}_LG12"
    shell:
        r"""
        module load hpc-env/13.1
        module load BCFtools/1.18-GCC-13.1.0
        module load PLINK/v1.9b7.4-x86_64

        bcftools view -r LG12:19982954-20482954,LG12:21977968-22477968 -Oz -o {params.tmp_vcf} {input.vcf}
        bcftools index {params.tmp_vcf}

        plink --vcf {params.tmp_vcf} \
              --allow-extra-chr \
              --make-bed \
              --out {params.tmp_prefix}

        plink --bfile {params.tmp_prefix} \
              --allow-extra-chr \
              --r2 \
              --ld-window-kb 5000 \
              --ld-window 99999 \
              --ld-window-r2 0 \
              --out ld/{wildcards.dataset}_LG12_12
        """